<a href="https://colab.research.google.com/github/Prasannas544/Business_Analytics/blob/main/11thJuly.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Array

In [1]:
#Array
arr = array(data=c(10,14,15,20,21,22,23,25),dim=c(2,2,2))

In [3]:
arr[1,2,1]

[1] 15

In [5]:
arr[,,1]

[,1] [,2]
[1,] 10   15  
[2,] 14   20

In [6]:
arr[1,,1]

[1] 10 15

In [14]:
eg_matrix1= array(data=1:40,dim=c(10,4))

In [15]:
eg_matrix1

[,1] [,2] [,3] [,4]
 [1,]  1   11   21   31  
 [2,]  2   12   22   32  
 [3,]  3   13   23   33  
 [4,]  4   14   24   34  
 [5,]  5   15   25   35  
 [6,]  6   16   26   36  
 [7,]  7   17   27   37  
 [8,]  8   18   28   38  
 [9,]  9   19   29   39  
[10,] 10   20   30   40

In [11]:
eg_matrix2 = matrix(data=1:40,nrow=10,ncol=4)

In [12]:
eg_matrix2

[,1] [,2] [,3] [,4]
 [1,]  1   11   21   31  
 [2,]  2   12   22   32  
 [3,]  3   13   23   33  
 [4,]  4   14   24   34  
 [5,]  5   15   25   35  
 [6,]  6   16   26   36  
 [7,]  7   17   27   37  
 [8,]  8   18   28   38  
 [9,]  9   19   29   39  
[10,] 10   20   30   40

In [16]:
#Element wise operations
eg_matrix1==eg_matrix2

[,1] [,2] [,3] [,4]
 [1,] TRUE TRUE TRUE TRUE
 [2,] TRUE TRUE TRUE TRUE
 [3,] TRUE TRUE TRUE TRUE
 [4,] TRUE TRUE TRUE TRUE
 [5,] TRUE TRUE TRUE TRUE
 [6,] TRUE TRUE TRUE TRUE
 [7,] TRUE TRUE TRUE TRUE
 [8,] TRUE TRUE TRUE TRUE
 [9,] TRUE TRUE TRUE TRUE
[10,] TRUE TRUE TRUE TRUE

In [18]:
dim(arr)

[1] 2 2 2

In [19]:
nrow(eg_matrix)

[1] 10

In [20]:
ncol(eg_matrix)

[1] 4

In [21]:
#Indexing and Modifying elements
my_mat=array(1:8,c(4,4))

In [22]:
my_mat

[,1] [,2] [,3] [,4]
[1,] 1    5    1    5   
[2,] 2    6    2    6   
[3,] 3    7    3    7   
[4,] 4    8    4    8

In [23]:
my_mat[2:4,2]

[1] 6 7 8

In [24]:
my_mat[1,]

[1] 1 5 1 5

In [25]:
my_mat[,1]

[1] 1 2 3 4

In [26]:
my_mat[,1] <- c(100,100,100,100)

In [29]:
my_mat

[,1] [,2] [,3] [,4]
[1,] 250  5    1    5   
[2,] 100  6    2    6   
[3,] 100  7    3    7   
[4,] 100  8    4    8

In [28]:
my_mat[1,1] <-250

In [31]:
my_mat[1:2,] <-array(data=c(1000,1000,1000,1000,1000,1000,1000,1000),dim=c(2,4))

In [32]:
my_mat

[,1] [,2] [,3] [,4]
[1,] 1000 1000 1000 1000
[2,] 1000 1000 1000 1000
[3,]  100    7    3    7
[4,]  100    8    4    8

In [33]:
#Combining two arrays/matrices
arr1=array(data=1:4,dim=c(2,2))
arr2=array(data=10:14,dim=c(2,2))

In [37]:
arr1

[,1] [,2]
[1,] 1    3   
[2,] 2    4

In [38]:
arr2

[,1] [,2]
[1,] 10   12  
[2,] 11   13

In [39]:
#Rows are combined
arr3=rbind(arr1,arr2)

In [40]:
arr3

[,1] [,2]
[1,]  1    3  
[2,]  2    4  
[3,] 10   12  
[4,] 11   13

In [ ]:
#Columns are combined

In [41]:
cbind(arr1,arr2)

[,1] [,2] [,3] [,4]
[1,] 1    3    10   12  
[2,] 2    4    11   13

In [42]:
#Error in rbind
arr1=array(data=1:4,dim=c(2,2))
arr2=array(data=10:14,dim=c(2,3))

In [43]:
rbind(arr1,arr2) # No. of columns should be same

ERROR: ignored

In [44]:
cbind(arr1,arr2)

[,1] [,2] [,3] [,4] [,5]
[1,] 1    3    10   12   14  
[2,] 2    4    11   13   10

In [45]:
#Error in cbind
arr1=array(data=1:4,dim=c(2,2))
arr2=array(data=10:14,dim=c(3,3))

In [46]:
cbind(arr1,arr2) # No.of rows should be same 

ERROR: ignored

In [47]:
#Matrix Operations
mat1 <- matrix(1:4,nrow=2,ncol=2)    #2x2
mat2 <- matrix(200:205,nrow=2,ncol=3)   #2x3

In [48]:
mat1*mat2

ERROR: ignored

In [51]:
#Matrix Operations
mat1 <- matrix(1:4,nrow=2,ncol=2)    #2x2
mat2 <- matrix(201:204,nrow=2,ncol=2)   #2x2

In [52]:
mat1

[,1] [,2]
[1,] 1    3   
[2,] 2    4

In [53]:
mat2

[,1] [,2]
[1,] 201  203 
[2,] 202  204

In [54]:
mat1 + mat2 # element wise addition

[,1] [,2]
[1,] 202  206 
[2,] 204  208

In [55]:
mat1*mat2 #element wise mulitplied

[,1] [,2]
[1,] 201  609 
[2,] 404  816

In [56]:
mat1 %*% mat2

[,1] [,2]
[1,]  807  815
[2,] 1210 1222

Factors

In [57]:
labels=c('Asia','Oceania','Antarctica','Europe','Africa','Europe','North America','South America','Africa')

In [ ]:
is.factor(labels)

In [62]:
typeof(labels)

[1] "character"

In [60]:
factor_labels <- factor(labels)

In [61]:
is.factor(factor_labels)

[1] TRUE

In [63]:
typeof(factor_labels)

[1] "integer"

In [64]:
as.integer(factor_labels)

[1] 3 6 2 4 1 4 5 7 1

In [71]:
factor_labels

[1] Asia          Oceania       Antarctica    Europe        Africa       
[6] Europe        North America South America Africa       
7 Levels: Africa Antarctica Asia Europe North America ... South America

In [65]:
nlevels(factor_labels)

[1] 7

In [66]:
altitude_levels=c('High',"Low","Medium","Low","High","Low")

In [67]:
altitude_factors=factor(altitude_levels)

In [68]:
as.integer(altitude_factors)

[1] 1 2 3 2 1 2

In [69]:
altitude_factors=factor(altitude_levels,order=TRUE,levels=c("Low","Medium","High"))

In [70]:
altitude_factors

[1] High   Low    Medium Low    High   Low   
Levels: Low < Medium < High

In [72]:
as.integer(altitude_factors)

[1] 3 1 2 1 3 1