<a href="https://colab.research.google.com/github/Prasannas544/Business_Analytics/blob/main/12th_July.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [28]:
#rbind and #cbind ,  Adding elements


countries_data<-data.frame(country=c('Portugal','France','UK'),
        population=c(10280000,66990000,66650000),
        EU=c(TRUE,TRUE,FALSE)
)

In [2]:
print(countries_data)

   country population    EU
1 Portugal   10280000  TRUE
2   France   66990000  TRUE
3       UK   66650000 FALSE


In [29]:
spain_data <- data.frame( country =c('Spain'),
                          population=c(572615474),
                          EU=c(TRUE)
                        )

In [4]:
print(spain_data)

  country population   EU
1   Spain  572615474 TRUE


In [30]:
countries_data <- rbind(countries_data,spain_data)

In [7]:
print(countries_data)

   country population    EU
1 Portugal   10280000  TRUE
2   France   66990000  TRUE
3       UK   66650000 FALSE
4    Spain  572615474  TRUE


In [8]:
capitals <- c("Lisbon","Paris","London","Madrid");

In [10]:
countries_data <- cbind(countries_data,capitals)

In [11]:
print(countries_data)

   country population    EU capitals
1 Portugal   10280000  TRUE   Lisbon
2   France   66990000  TRUE    Paris
3       UK   66650000 FALSE   London
4    Spain  572615474  TRUE   Madrid


In [12]:
str(countries_data)

'data.frame':	4 obs. of  4 variables:
 $ country   : chr  "Portugal" "France" "UK" "Spain"
 $ population: num  1.03e+07 6.70e+07 6.66e+07 5.73e+08
 $ EU        : logi  TRUE TRUE FALSE TRUE
 $ capitals  : chr  "Lisbon" "Paris" "London" "Madrid"


In [32]:
#Removing elements from dataframe
countries_data <- countries_data[c(-2,-4),]

In [33]:
print(countries_data)

   country population    EU
1 Portugal   10280000  TRUE
3       UK   66650000 FALSE


In [19]:
countries_data[,'EU']<-NULL # removing columns

In [23]:
print(countries_data)

   country population capitals
1 Portugal   10280000   Lisbon
2   France   66990000    Paris


In [26]:
summary(countries_data)


   country            population         capitals        
 Length:2           Min.   :10280000   Length:2          
 Class :character   1st Qu.:24457500   Class :character  
 Mode  :character   Median :38635000   Mode  :character  
                    Mean   :38635000                     
                    3rd Qu.:52812500                     
                    Max.   :66990000                     

Lists

In [35]:
#Create lists 
vec=c(1,2,"3")
typeof(vec)

[1] "character"

In [36]:
my_list=list(1,2,"3")

In [37]:
typeof(my_list)

[1] "list"

In [38]:
multi_object <- list(
                      c(1,2,3),
                      array(1:4,dim=c(2,2)),
                      TRUE

                    )

In [39]:
print(multi_object)

[[1]]
[1] 1 2 3

[[2]]
     [,1] [,2]
[1,]    1    3
[2,]    2    4

[[3]]
[1] TRUE



In [40]:
#Names property 
names(multi_object) <- c("Vector","Array","Logical")

In [41]:
print(multi_object)

$Vector
[1] 1 2 3

$Array
     [,1] [,2]
[1,]    1    3
[2,]    2    4

$Logical
[1] TRUE



In [42]:
length(multi_object)

[1] 3

In [43]:
str(multi_object)

List of 3
 $ Vector : num [1:3] 1 2 3
 $ Array  : int [1:2, 1:2] 1 2 3 4
 $ Logical: logi TRUE


In [44]:
#Assigning names automatically 
multi_obj <-list(

"Vector"=c(1,3,5,7),
"Array"=array(1:4,dim=c(2,2)),
"Boolean"= c(TRUE,FALSE)


)

In [45]:
print(multi_obj)

$Vector
[1] 1 3 5 7

$Array
     [,1] [,2]
[1,]    1    3
[2,]    2    4

$Boolean
[1]  TRUE FALSE



In [46]:
# Indexing Lists 
multi_object[1]   # accesing the sub-element  # view-only mode

$Vector
[1] 1 2 3

In [49]:
multi_object[[1]]   # Accessing the underlying element # edit mode 

[1] 1 2 3

In [50]:
vect=c(1,5,9)

In [54]:
vect

[1] 1 5 9

In [56]:
multi_object[[1]][1]

[1] 1

In [58]:
multi_object[[2]][1:2,2]

[1] 3 4

In [59]:
multi_object[c(1,2)]

$Vector
[1] 1 2 3

$Array
     [,1] [,2]
[1,]    1    3
[2,]    2    4

In [64]:
multi_object[["Vector"]]

[1] 1 2 3

In [63]:
multi_object$Array

[1] 4

In [65]:
#Changing and adding elements to list 
example_list = list(c('a','b','c'), array(1:10,dim=c(2,5)))

In [66]:
#adding new element to the list 
example_list[[3]] <- c(1,2,3)

In [67]:
example_list

[[1]]
[1] "a" "b" "c"

[[2]]
     [,1] [,2] [,3] [,4] [,5]
[1,]    1    3    5    7    9
[2,]    2    4    6    8   10

[[3]]
[1] 1 2 3

In [68]:
length(example_list)

[1] 3

In [69]:
example_list[2] <-TRUE #Replace/Overwrite

In [70]:
example_list

[[1]]
[1] "a" "b" "c"

[[2]]
[1] TRUE

[[3]]
[1] 1 2 3

In [71]:
example_list[[10]] <- c(8,9,10)

In [72]:
length(example_list)

[1] 10

In [73]:
print(example_list)

[[1]]
[1] "a" "b" "c"

[[2]]
[1] TRUE

[[3]]
[1] 1 2 3

[[4]]
NULL

[[5]]
NULL

[[6]]
NULL

[[7]]
NULL

[[8]]
NULL

[[9]]
NULL

[[10]]
[1]  8  9 10

